#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_PAC_VERSION=${VERSION_STRING[2]}
ELECTRUM_PAC_VERSION=${ELECTRUM_PAC_VERSION#\'}
ELECTRUM_PAC_VERSION=${ELECTRUM_PAC_VERSION%\'}
export ELECTRUM_PAC_VERSION
